package com.orm;



/**
 * Usertab generated by MyEclipse - Hibernate Tools
 */

public class Usertab  implements java.io.Serializable {


    // Fields    

     private Integer userid;
     private String username;
     private String userpwd;


    // Constructors

    /** default constructor */
    public Usertab() {
    }

    
    /** full constructor */
    public Usertab(String username, String userpwd) {
        this.username = username;
        this.userpwd = userpwd;
    }

   
    // Property accessors

    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getUserpwd() {
        return this.userpwd;
    }
    
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }
   








}